number1=input('Enter number1')
number2=input('Enter number2')
print(number1,number2)
sum=number1+number2
print(sum)
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
multiplication=int(number1)*int(number2)
division=int(number1)/int(number2)
print(difference,multiplication,division)
number3=input('enter number3')
sum=int(number1)+int(number2)+int(number3)
difference=int(number1)-int(number2)-int(number3)
multiplication=int(number1)*int(number2)*int(number3)
division=(int(number1)/int(number2))/int(number3)
print(sum,difference,multiplication,division)
import math
print(math.sqrt(9))
print(math.sin(9))
print(math.tan(9))
print(math.cos(9))
print(math.exp(9))
print(math.fabs(9))
print(math.log(9))
print(math.sinh(9))
print(math.tanh(9))
print(math.cosh(9))
c